---
title: "README"
author: "Ligaya Breemer"
date: "4/18/2022"
output: pdf_document
---

This Github repository contains the various scripts used to conduct my master thesis project. The following is a description of the files contained in the repository.

*analysis of deviance.R*
This `R` script contains the code that was used to analyze the contributions of the auxiliary variables **X** to the target variable *Y*. 

*Analysis.R* 
This `R` script contains the code that was used to analyze the output from *PILOT_STUDY.R*. The code needs to be edited to obtain results for the different populations (instructions are at the top of the script).

*AnalysisS2.R*
This `R` script contains the code that was used to analyze the output from *SIM2.R*. The code needs to be edited to obtain results for the different populations (instructions are at the top of the script).

*EmpiricalData.R*
This `R` script contains the code that was used to conduct the empirical data study. The Labor Force Survey data that was used in this example is confidential and therefore not publicly available. Upon request, legitimate researchers can be granted access to the data.

*MRNNMI_fun.R*
This `R` script contains a function that applies MRNNMI to a dataframe and returns imputated data sets. 

*PILOT_STUDY.R*
This `R` script contains the data generation code as well as the code for the first half of the simulation study (excluding analysis of the output).

*SIM2.R*
This `R` script contains the code for the second half of the simulation study (excluding analysis of the output).
